### PR TITLE
Add missing dependencies to Debian package

### PR DESCRIPTION
**Pull request by nRaecheR**
This resolves the missing dependencies to:

- libpython3.12
- libfftw3

### CODE REVIEW

**Comment by Lamarqe** [comment]
Thank you.

I prefer to assure compatibility with most recent python releases.
So I would refer only to `python3` instead of `libpython3.12`.

Could you please confirm that this works as expected, too?

**Comment by nRaecheR** [comment]
No, on Ubuntu 24.04 it will only work when stating the libpython3.12 library with full version (3.12). Using `python3` or `libpython3` won't work

**Comment by Lamarqe** [comment]
Into which error message do you run when you only specifiy `python3`?

**Comment by nRaecheR** [comment]
> mpdcast_dab.__main__ - WARNING: libpython3.12.so.1.0: cannot open shared object file: No such file or directory

**Comment by Lamarqe** [comment]
I don't understand this this problem. I also cannot reproduce it.

libfftw was definitely missing. I fixed this.

The python dependency should not be necessary. The control file contains multiple dependencies to python packages which have listed python as a dependency themselves.
Still, I added python3 explicitly now. This makes sense.

Regarding python vs libpython3.12: I consider this wrong. Trying the dockerfile from the issue you had created earlier works okay: The container runs into a python error regarding startup parameter. However, python itself starts fine.

**Comment by nRaecheR** [comment]
Try this Dockerfile:

```
FROM ubuntu:24.04

RUN set -xe \
    && apt update \
    && apt install -y software-properties-common \
    && add-apt-repository ppa:lamarqe/ppa \
    && apt update \
    && apt install -y mpdcast-dab \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/mpdcast_dab"]
CMD [ "--disable-mpdcast"] 
```

build it with

`podman build --tag mpdcast_dab -f ./Dockerfile`

then run it without hardware mapping 

`podman run -v ./mpd.conf:/etc/mpd.conf:ro -v /etc/localtime:/etc/localtime:ro --name mpdcast --rm mpdcast_dab
`

All with root permissions

The resulting output is

```
mpdcast_dab.__main__ - WARNING: Disabling MPD cast functionality
mpdcast_dab.__main__ - WARNING: Failed to load DAB+ library
mpdcast_dab.__main__ - WARNING: libpython3.12.so.1.0: cannot open shared object file: No such file or directory
mpdcast_dab.__main__ - ERROR: Fatal. Both MpdCast and DAB processing failed to initialize. Exiting.
```

**Comment by Lamarqe** [comment]
Should be fixed with https://github.com/Lamarqe/mpdcast-dab/commit/5b5387e642976ce04c725e15fa4e032280e6697c
Please confirm.

**Comment by nRaecheR** [comment]
Yes, the current ppa debian package installs now without adding additional dependencies

**Pull request closed without merging**
